name: thiran_tech_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 
  flutter_bloc: ^9.0.0
  http: ^1.3.0
  sqflite: ^2.3.3 
  path: ^1.9.0
  firebase_core: ^3.10.1
  firebase_database: ^11.3.1
  firebase_messaging: ^15.2.1
  mailer: ^6.4.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_email_sender: ^6.0.3
  workmanager: ^0.5.2
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.2
  cloud_firestore: ^5.6.2
  timezone: ^0.10.0
  file_picker: ^8.3.1
  firebase_storage: ^12.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
